### ISSUE TITLE
[FR] latest update port to here

### ISSUE THREAD

**Issue by warior456** [jadestudios/discord-music-player#18]
sushibtw discord-music-player has had an update

**Comment by thenerdoflight** [comment]
From what I can tell, the only difference following upstream would be package updates. Unless it's necessary, I do not plan on updating to that.

**Comment by warior456** [comment]
he closed issues as fixed

**Comment by thenerdoflight** [comment]
I see what you mean. He fixed an issue that you were having.

**Comment by warior456** [comment]
yeah and i switched to this right after that

**Comment by thenerdoflight** [comment]
Pulled upstream in latest release.
