### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'display_name')

### ISSUE THREAD

**Issue by Alejandro-AP00** [jadestudios/discord-music-player#21]
**Bug Description**
The owner property in the Spotify playlist does not exist when getting data. This is happening in the playlist Util

**Reproduction Steps**
1. Use the queue.playlist method with any Spotify playlist
2. An error about the display_name appears

**Comment by thenerdoflight** [comment]
Thanks for the report! Please update to latest version (az22).

I don't use playlists often let alone Spotify playlists, so this was a great catch.

**Comment by Alejandro-AP00** [comment]
No problem, thanks for the quick fix!
