### ISSUE TITLE
[FR] Add Support For Adding Cookies to Play Age Restricted Videos

### ISSUE THREAD

**Issue by BennyDaBee** [jadestudios/discord-music-player#32]
**Is your feature request related to a problem? Please describe.**

Currently I am not sure of a way to add a cookie to be able to play Age Restricted videos with the bot

**Describe the solution you'd like**

Add a variable we can define in docker that lets us supply a cookie that is added to the request to authenticate for Age Restricted videos. 

**Describe alternatives you've considered**

N/A

**Additional Comments**

I was able to accomplish this on Sushis distro with ytdl by adding in Queue.js requestOptions  
requestOptions: this.player.options.ytdlRequestOptions ?? {headers:{cookie:'COOKIE GOES HERE'}},

**Comment by thenerdoflight** [comment]
Hi @BennyDaBee ,

Thank you for the Feature Request!

I personally do not use cookies with this package, so I'm not too sure how to implement it. 
Also, it doesn't help that I ripped out the RequestOptions interface many commits back. 

Feel free to open a PR if you have a solution in mind, but I will not be implementing this for the time being.
I might revisit this when I have more time.

As always, thank you!
