### ISSUE TITLE
[BUG] 403 on Any Videos

### ISSUE THREAD

**Issue by BennyDaBee** [jadestudios/discord-music-player#40]
**Bug Description**
Getting 403 error on any youtube video 

**Reproduction Steps**
1. Just try to use a youtube video

**Attachments**

![image](https://github.com/user-attachments/assets/b9b6b03a-6456-42fa-a5a3-65a45a9617ec)

**Versioning:**
- OS: Ubuntu 22.04
- Node Version v22
- Module Version az29

**Comment by thenerdoflight** [comment]
Hi @BennyDaBee ,

Thank you for the bug report!

Please provide more details on reproducing this issue.
Every release goes through a simple E2E flow, and no issues were seen.

**Comment by BennyDaBee** [comment]
When providing a youtube link to queue.play() it will throw a 403 error regardless of what the video is.

**Comment by thenerdoflight** [comment]
Thank you for the response.

Your statement regarding " 403 error regardless of what the video is" is clearly not the case. If it was, it would have been caught before release. 

As usual, please provide more details (i.e, the url you are using, and the stack trace when it errors out), so I can better assist you.

**Comment by BennyDaBee** [comment]
https://www.youtube.com/watch?v=6Zbi0XmGtMw&pp=ygUPV2UgbGlrZSB0byBwYXJ5 - Example URL, again it happens with any video. Here is the error I see in the logs. 

```https://www.youtube.com/watch?v=6Zbi0XmGtMw&pp=ygUPV2UgbGlrZSB0byBwYXJ5
WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
WARNING: Could not parse n transform function.
Please report this issue with the "1722106383910-base.js" file on https://github.com/distubejs/ytdl-core/issues.
Stream URL may be slow but still works.
node:events:511
    throw err; // Unhandled 'error' event
    ^
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Status code: 403')
    at Player.emit (node:events:509:17)
    at StreamConnection.<anonymous> (/Bot/node_modules/discord-music-player/dist/managers/Queue.js:185:47)
    at StreamConnection.emit (node:events:520:28)
    at AudioPlayer.<anonymous> (/Bot/node_modules/discord-music-player/dist/voice/StreamConnection.js:91:18)
    at AudioPlayer.emit (node:events:520:28)
    at Encoder.onStreamError (/Bot/node_modules/discord-music-player/node_modules/@discordjs/voice/dist/index.js:1122:14)
    at Object.onceWrapper (node:events:635:26)
    at Encoder.emit (node:events:532:35)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3) {
  code: 'ERR_UNHANDLED_ERROR',
  context: 'Status code: 403'
}
```

**Comment by BennyDaBee** [comment]
My apologise, was due to my outdated ytdl-core. I will close this.
