### ISSUE TITLE
[BUG] Sign in to confirm you’re not a bot

### ISSUE THREAD

**Issue by EnreLyugi** [jadestudios/discord-music-player#41]
When trying to play a song, it generates an error saying "Sign in to confirm you’re not a bot"

**Comment by thenerdoflight** [comment]
Hi @EnreLyugi ,

Thank you for the bug report.
This issue looks similar to an ongoing issue that is plaguing a lot of other similar packages.

Since I don't write/ maintain the portion that interfaces with Youtube, I am waiting for a fix as well.

**Comment by thenerdoflight** [comment]
Fixed in az30
